trigger:
  - master

pool:
  name: Azure CI
  demands: npm

steps:
  - task: Cache@2
    displayName: "Cache npm Dependencies"
    inputs:
      key: "**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json"
      path: "$(Build.SourcesDirectory)/node_modules"
      cacheHitVar: CacheRestored

  - task: Npm@1
    displayName: "npm ci"
    inputs:
      command: ci
      verbose: false
    condition: eq(variables['CacheRestored'],False)

  - script: npm run test:ci
    name: Test

  - task: PublishTestResults@2
    displayName: Test Report
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "./coverage/fsms-angular-pubsub/test-report.xml"
      mergeTestResults: true
    condition: |
      succeeded()
