# Trigger CI automatically whenever main branch is changed
name: Angular Pubsub Azure CI Pipeline
pool:
  vmImage: "ubuntu-latest"

strategy:
  matrix:
    node_14_x:
      node_version: 14.x
    # node_14_x:
    # node_version: 14.x

variables:
  AUTH_NPMTOKEN: $(NPM_TOKEN) # Mapping secret var
  AUTH_GHTOKEN: $(GH_TOKEN) # Mapping secret var
  IS_PULLREQUEST: $[eq(variables['Build.Reason'], 'PullRequest')]
  NPM_CACHE_DIR: $(Pipeline.Workspace)/.npm

trigger:
  - main

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - task: Cache@2 # Cache Node packages on build agent
    displayName: "Cache npm Dependencies"
    inputs:
      key: "**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json"
      path: $(NPM_CACHE_DIR)
      cacheHitVar: CacheRestored

  - task: Npm@1 # Install npm packages on your build agent
    displayName: "Npm CI"
    inputs:
      command: ci
      verbose: false
    condition: eq(variables['CacheRestored'],False)

  - script: npm run test:ci # Run unit tests
    enabled: true
    displayName: Test

  - task: PublishTestResults@2 # Publish test results
    displayName: Test Report
    enabled: true
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "./coverage/fsms-angular-pubsub/test-report.xml"
      mergeTestResults: true
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1 # Publish code coverage results
    enabled: true
    displayName: Code Coverage
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "./coverage/fsms-angular-pubsub/cobertura-coverage.xml"
    condition: succeededOrFailed()

    # Package web apps -->
  - script: npm run build:ci # Build Angular Project
    displayName: Build
    enabled: true

  - script: node ./tools/version.js $(Build.BuildId)
    displayName: Update Version

  - bash: | # Grab the package version
      v=`node -p "const p = require('./package.json'); p.version;"`
      echo "##vso[task.setvariable variable=packageVersion]$v"
    displayName: Package Version

  - script: | # Update Build
      echo "##vso[build.updatebuildnumber]$(packageVersion)_$(Build.SourceBranchName)"
    enabled: true
    displayName: Update Build Number

  - script: npm run changelog # Change Log
    displayName: Changelog

  - script: npm run copyfiles # Copy Changelogs
    displayName: Copy Files

  - script: | # Publish a module to a npm registry
      npm config set //registry.npmjs.org/:_authToken=$(AUTH_NPMTOKEN)
      npm config set scope "@fsms"
      # npm config list
      # npm --version
      npm publish --access public
    displayName: Publish NPM
    workingDirectory: "./dist/fsms-angular-pubsub"
    condition: |
      and(
        succeeded(),
        ne(variables['IS_PULLREQUEST'], 'true')
      )

  - script: | # Publish a module to a github npm registry
      npm config set registry=https://npm.pkg.github.com/fullstackmaster1
      npm config set scope "@fsms"
      # npm config list
      # npm --version
      npm publish --access public
    displayName: Publish GitHub
    workingDirectory: "./dist/fsms-angular-pubsub"
    condition: |
      and(
        succeeded(),
        ne(variables['IS_PULLREQUEST'], 'true')
      )
