# Trigger CI automatically whenever main branch is changed
name: Angular Pubsub Azure CI Pipeline
pool:
  vmImage: "ubuntu-latest"

trigger:
  - main

variables:
  IS_PULLREQUEST: $[eq(variables['Build.Reason'], 'PullRequest')]

steps:
  - task: Cache@2
    displayName: "Cache npm Dependencies"
    inputs:
      key: "**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json"
      path: "$(Build.SourcesDirectory)/node_modules"
      cacheHitVar: CacheRestored

  - task: Npm@1
    displayName: "Npm CI"
    inputs:
      command: ci
      verbose: false
    condition: eq(variables['CacheRestored'],False)

  - script: |
      export tag=$(node ./tools/version.js $(Build.BuildId) $(Build.SourceBranchName))
      echo $tag
      echo "##vso[build.updatebuildnumber]$tag"
    displayName: Update Build Number

  - script: echo "$(Build.BuildNumber)"
    displayName: "New Build Number"

  - script: npm run test:ci
    enabled: false
    displayName: Test

  - task: PublishTestResults@2
    displayName: Test Report
    enabled: false
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "./coverage/fsms-angular-pubsub/test-report.xml"
      mergeTestResults: true
    condition: |
      succeeded()

  - task: PublishCodeCoverageResults@1
    enabled: false
    displayName: Code Coverage
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "./coverage/fsms-angular-pubsub/cobertura-coverage.xml"
    condition: |
      succeeded()

  - script: npm run build:ci
    displayName: Build
    enabled: true

  - task: CopyFiles@2
    displayName: Copy .NPMRC
    inputs:
      sourceFolder: './projects/fsms-angular-pubsub'
      Contents: '.npmrc'
      targetFolder: './dist/fsms-angular-pubsub'

  - task: CopyFiles@2
    displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
    enabled: true
    inputs:
      SourceFolder: "./dist/fsms-angular-pubsub"
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: ArchiveFiles@2
    displayName: "Archive $(Build.ArtifactStagingDirectory)"
    enabled: true
    inputs:
      rootFolderOrFile: "$(Build.ArtifactStagingDirectory)"
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    enabled: true

  - script: echo './dist/fsms-angular-pubsub/.npmrc'

  - script: |
      echo "publishing to npm repository"
      node ./tools/publish.js 'fsms-angular-pubsub'
    enabled: true
    displayName: Publish NPM
    condition: |
      and(
        succeeded(),
        ne(variables['IS_PULLREQUEST'], 'true')
      )
