# Trigger CI automatically whenever main branch is changed
name: Angular Pubsub Azure CI Pipeline
pool:
  vmImage: "ubuntu-latest"

trigger:
  - main

steps:
  - task: Cache@2
    displayName: "Cache npm Dependencies"
    inputs:
      key: "**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json"
      path: "$(Build.SourcesDirectory)/node_modules"
      cacheHitVar: CacheRestored

  - task: Npm@1
    displayName: "npm ci"
    inputs:
      command: ci
      verbose: false
    condition: eq(variables['CacheRestored'],False)

  - script: echo "##vso[task.setvariable variable=tag]$(node ./tools/version.js)"
    displayName: New Version

  - script: echo "##vso[build.updatebuildnumber]$tag"
    displayName: "Update Build Number"

  - script: echo "$(Build.BuildNumber)"
    displayName: "New Build Number"

  - script: npm run test:ci
    displayName: Test

  - task: PublishTestResults@2
    displayName: Test Report
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "./coverage/fsms-angular-pubsub/test-report.xml"
      mergeTestResults: true
    condition: |
      succeeded()

  - task: PublishCodeCoverageResults@1
    enabled: true
    displayName: Code Coverage
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "./coverage/fsms-angular-pubsub/cobertura-coverage.xml"
    condition: |
      succeeded()

  - script: npm run build:ci
    displayName: Build

  - script: npm run npmPublish
    displayName: Npm Publish
