name: build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # caching node modules
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:ci

      - name: Generate tag and ChangeLog
        run: |
          git config user.name rupeshtiwari
          git config user.email roopkt@gmail.com
          npx standard-version --release-as patch --skip.commit

      - name: publish tag
        id: publish_tag
        run: |
          git push --follow-tags origin main
          echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)

      - name: Read Tag Name
        run: echo Git Tag Name is ${{ steps.publish_tag.outputs.tag_name }}

      - name: Build
        run: npm run build:ci

      - run: NPM Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: dis/fsms-angular-pubsub

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist

      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_coverage
          path: coverage

      - name: Create release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          release_name: Release ${{ steps.publish_tag.outputs.tag_name }}
          tag_name: ${{ steps.publish_tag.outputs.tag_name }}
          body_path: CHANGELOG.md
