name: build

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # caching node modules
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:ci

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v1.8
        if: always()
        with:
          files: ./coverage/fsms-angular-pubsub/test-report.xml

      - name: Publish Code Coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        if: always()
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          lcov-file: ./coverage/fsms-angular-pubsub/lcov.info

      - name: Generate tag and ChangeLog
        if: success()
        run: |
          git config user.name rupeshtiwari
          git config user.email roopkt@gmail.com
          npx standard-version --release-as patch --skip.commit

      - name: Publish Tag
        id: publish_tag
        run: |
          git push --follow-tags origin main
          echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)

      - name: Read Tag Name
        run: echo Git Tag Name is ${{ steps.publish_tag.outputs.tag_name }}

      - name: Build
        run: npm run build:ci

      - name: NPM Publish
        run: npm publish --access public
        working-directory: ./dist/fsms-angular-pubsub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist

      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_coverage
          path: coverage

      - name: Create release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          release_name: Release ${{ steps.publish_tag.outputs.tag_name }}
          tag_name: ${{ steps.publish_tag.outputs.tag_name }}
          body_path: CHANGELOG.md
